# General Lab Policy

## Work hours
One of the benefits of a career in academic research is that it is typically more flexible than other kinds of jobs. However, you should still treat it like a job. If you are employed for 40 hours a week, you should be working 40 hours a week. This applies to lab staff members (e.g., the lab coordinator) and postdocs. You are not required to work over-time. For graduate students, I recognize that you have other demands on your time like classes but I still expect that you will be regularly engaged in your research.

Lab staff members are expected to keep regular hours (e.g., somewhere in the ballpark of 9-5). Graduate students and postdocs have more flexibility. I recognize that research timelines and creativity not always fitting into a strict 9-to-5 framework. However, in order to encourage lab interaction, I expect that all lab members will be in the lab, at minimum, most weekdays between 10am and 3pm or so. If you’re going to be taking off from work on a normal workday (i.e., taking vacation or a personal or sick day), please let Qing know.

I encourage everyone to manage their time in a way that fosters both professional growth and personal well-being. Flexibility is great, but so is mutual respect for the team’s time and responsibilities.

## PI availability
I will be working on campus and available for meetings most days of the week. If my door is open, feel free to pop in. If my door is closed, that usually means I am in a meeting or trying to be laser-focused on writing. In that case, please send me a message or try again later rather than knocking—unless it’s an emergency. I’m also happy to set ad-hoc meetings to discuss anything over and above our weekly lab and individual meetings.
When working remotely, I’ll be similarly available over Slack and for ad-hoc meetings during regular office hours. But I try to turn my notifications off when I’m going to be concentrating on something else for a long stretch. 

## Safety
Lab safety is of utmost priority—not just to protect yourself, but everyone around you. Please adhere to all safety codes required by the school and wear proper personal protective equipment (PPE) when necessary. We have many chemicals and biohazard materials, please follow guidelines when using or disposing them. More information can be found on [UMass Chan Environmental Health & Safety](https://umassmed.sharepoint.com/sites/ehs-intranet)

## Presentations
I encourage you to seek out opportunities to present your research to the department, research community, or general public. If you are going to give a presentation (including posters and talks), please be prepared to give a practice presentation to the lab at least one week ahead of time. Not only will this help you feel comfortable with the presentation, it will give you time to implement any feedback. I care about practice presentations because __a)__ presenting your work is a huge part of being successful in science and it's important that you practice those skills as often as possible, and __b)__ you are going to be representing not only yourself but also the rest of the lab.

There is a lab template for posters that you are free to modify as you see fit, but the header and general aesthetic should stay similar. If you have ideas for how to improve the poster template, please show the lab so we can decide whether to implement them as a group. This will help increase the visibility of our lab at conferences. There is no template for talks, and I encourage you to use your own style of presentation as long as it is polished and clear.

When making figures, it is helpful if you follow a few color-coding conventions, so that it’s easier to keep things consistent when I present your work in talks. There is a common coloring scheme for general proteomics workflow available in the shared Illustrator document. There are also common figures and illustrations available. If you have modifications or a new illustration, add a new artboard and show off your work!

## Lab travel
I encourage all lab members to attend conferences. They are great opportunities to advocate for your science, get inspired, and build connections and collaborations. The lab will typically pay for full-time lab members to present their work at major conferences (e.g., ASMS, HUPO, GRC), as long as there is funding to do so. In general, the work should be "new" in that it has not been presented previously, and it should be appropriate for the conference. This will usually result in one conference per year. When I set our grant budgets, I estimate $1500 per trip, so your reimbursable costs should be around that amount or less. 

## Deadlines
If you need something from me by a particular deadline, please inform me as soon as you are aware of the deadline so that I can allocate my time as efficiently as possible. I will expect at least one week’s notice, but I greatly prefer two weeks’ notice. I will require two weeks’ notice for letters of reference. Please note that this applies to reading/commenting on abstracts, papers, and manuscripts, in addition to filling out paperwork, etc. Reminder messages are appreciated as well!

## Reference Letter
Letters of recommendation are one of the many benefits of working in a research lab. I will write a letter for any student or lab member who has spent at least one year in the lab. Letters will be provided for shorter-term lab members in exceptional circumstances (e.g., new graduate students or postdocs applying for fellowships). I maintain this policy because I do not think that I can adequately evaluate someone who has been around for less than a year.
To request a letter of recommendation, please adhere to the deadline requirements described above. Send me your current CV and any relevant instructions for the contents of the letter. If you are applying for a grant, send me your specific aims or a short summary of the grant. You are advised to send me a reminder message close to the letter deadline.

## Funding
Funding for the lab comes from a variety of sources, including federal agencies (e.g., NIH, NSF), private foundations (e.g., American Heart Association), and internal funds from UMass Chan. I will oversee all aspects of the financial management of our funding sources. However, it is important to me to be transparent about where research money comes from and how it's spent. You can find some details on our internal lab website, but please do not hesitate to ask if you want to know more details. In general, external funds tend to be restricted to expenses related to a particular project or set of projects, whereas some of the internal funds are flexible in that they can be used for any justifiable work-related purpose. 
All research funded by external grants must acknowledge the funding agency and grant number upon publication. This is essential for documenting that we are turning their money into research findings. We must also submit a yearly progress report describing what we have accomplished. Lab members involved in the research will be asked to contribute to the progress report.
