# Instrumentation

## Mass Spectrometer
Mass spectrometry has become an essential tool in quantitative proteomics, where a deep insight into proteotype can be obtained to understand mechanisms underlying diseases and to promote translational therapeutic development. Our lab has two of the most advanced mass spectrometers, the Orbitrap Eclipse and the Orbitrap Astral. They are very expensive as you probably can tell from all the nuts and bolts, thanks to Thermo! Through your time in the lab, I highly recommend learning some basics from the [Literature to Warm Up] and familiarizing yourself with how to operate and even program these machines; you will be amazed.

That said, these are delicate instruments that can break. If you encounter any issues during operation (including hardware malfunctions or software faults), please alert me immediately, and whoever is the primary instrument administrator! These problems cannot be ignored, as they are likely to cause considerable harm to the instruments if left unattended. Unaddressed issues can also lead to expensive repairs, potentially costing tens of thousands of dollars.If you notice significant degradation of instrument performance during or after your runs, alert both Qing and the next user so that samples are not lost!

## HPLC
Separation or enrichment of peptides, proteins, and small molecules using high performance liquid chromatography (HPLC) is an integral part of our workflows. Normal HPLCs are often quite robust, while nano-HPLCs can be prone to failure due to their high operational pressures. As with the mass spectrometers any issues with the hardware or software need to be addressed immediately.
